services:
  mysql:
    image: mysql:8
    restart: always
    ports:
      - '3308:3306'
    volumes:
      - ./mysql/data/:/var/lib/mysql/
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: ${mysql_pwd}
      MYSQL_DATABASE: grad_evaluation
    command:
      --max_connections=2500
    healthcheck:
      # test: mysql --user=root --password=1157 -e "select 1;"
      test: mysql -uroot -p$$MYSQL_ROOT_PASSWORD -e "select 1;"
      interval: 10s
      timeout: 3s
      retries: 3

  openjdk:
    image: openjdk:21
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - '8080'
    volumes:
      - ./openjdk/:/home/
    environment:
      dhost: mysql:3306
      dusername: root
      dpassword: ${mysql_pwd}
      secretkey: ${secretkey}
      TZ: Asia/Shanghai
    command: java -jar /home/graduate-recommendation-evaluation.jar --spring.profiles.active=prod

  nginx:
    image: nginx:1.25
    restart: always
    depends_on:
      - openjdk
    ports:
      - '8081:80'
    environment:
      - bhost=openjdk:8080
    volumes:
      - ./nginx/html:/usr/share/nginx/html:ro
      - ./nginx/templates:/etc/nginx/templates
